In [1]:
import numpy as np

def generate_partitions(nitems, step_size, N, method='n_steps'):
    # generate partitions based on N steps per partition
    if method == 'n_steps':
        partitions = np.arange(0, nitems, step_size * N)
        if partitions[-1] != nitems:
            partitions = np.append(partitions, nitems)

    # generate partitions based on N partitions
    if method == 'n_partitions':
        partitions = np.linspace(0, nitems, N, dtype=int).tolist()
    return partitions

In [2]:
generate_partitions(1000, 100, 3, method='n_steps')

array([   0,  300,  600,  900, 1000])

In [6]:
generate_partitions(1000, 100, 4, method='n_partitions')

[0, 333, 666, 1000]

In [12]:
def aggregate(elem1,elem2):
    if elem1 == -1:
        return elem2
    else:
        return elem1


In [16]:

agg_func = np.vectorize(aggregate)

m2 = -1 * np.ones((100,100))

m1 = np.ones((100,100))


In [14]:

%timeit agg_func(m1,m2)

750 µs ± 1.23 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [17]:
agg_func(m1,m2)

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [1]:
import tables

[2 3 1]
